### ISSUE TITLE
Please improve contrast on text selection

### ISSUE THREAD

**Issue by Meligy** [kaiusl/pastel_evening_vscode#1]
*Make sure to use the latest version of the theme before adding a report.*
✅ v0.3.0
**Describe the bug**
I would like the text selection background to be a bit easier to distinguish.

Here I searched for "workbench", selected "Pastel":

<img width="979" alt="image" src="https://github.com/kaiusl/pastel_evening_vscode/assets/171637/8f64eeae-1920-4cdf-8986-d034bf5f7ec2">

Now with the same selection, I just hovered over the closing double quote of the string value:

<img width="1019" alt="image" src="https://github.com/kaiusl/pastel_evening_vscode/assets/171637/cda5747d-7ffb-45fd-a2ec-3cf77dc4c10c">

Another example, this time selecting "centeredLayoutAutoResize":
<img width="990" alt="image" src="https://github.com/kaiusl/pastel_evening_vscode/assets/171637/fe9da513-11cd-43d4-86b3-d922282353f6">

More examples:

Selecting "get":

<img width="956" alt="image" src="https://github.com/kaiusl/pastel_evening_vscode/assets/171637/3ff4bd7a-d9a9-4265-ad90-1bfa0d1a2fcf">
(It's worth noting that the contrast looks more obvious in the screenshot than on real screen for some reason)
<br />
<br />
  
Selecting "the":

<img width="953" alt="image" src="https://github.com/kaiusl/pastel_evening_vscode/assets/171637/6aaf6d8b-e722-47a1-9f96-424fbdc2964f">

**Extra information:**
- VS Code version: [e.g. 1.74]
   1.86.0-insider
- Language and/or file extension: [e.g. .jsx]
  I see it in JSON, TypeScript, C#. It's probably not language specific
- All relevant used extensions and their versions: [e.g. rust-analyzer v0.4.12]
  Not sure if any extensions are relevant to this specific issue

If you can think of any other relevant information to help find and fix the bug quickly, please add it.

Again: It's worth noting that the contrast looks more obvious in the screenshot than on real screen for some reason. So, I struggle more using the screen than it seems in them.

**Comment by Meligy** [comment]
Using the template, I forgot to first say thanks a lot for the great theme.

I have found very few extensions other than the one that ships with the C# extension (not even the VS Code default ones) to have a proper highlighting of interfaces vs classes etc.

**Comment by kaiusl** [comment]
I see what you mean but I'm not quite sold on changing it at the moment. The selection background was meant to be relatively subtle.

However you can always change the colors to your liking through "settings.json". 
To change the selection background add the following lines with any color (ones in the snippet are the default ones):
```json
"workbench.colorCustomizations": {
    "[Pastel Evening Dark]": {
        "editor.selectionBackground": "#324454ff",
        "editor.inactiveSelectionBackground": "#2b3947ff",
    }
},
```

**Comment by Meligy** [comment]
Thanks for the guidance.

As I report this, I realise there are 2 different issues here:

1. How the selection is subtle, which can be argued whether it's a bug or a matter of taste. That was my intended purpose of the issue.

2. How the selection color matches the hover effect of many other tokens. Like a reference match or a string highlight.  
  <span></span>
  See the 2nd picture in my issue. Here's another recreation:
  ![image](https://github.com/kaiusl/pastel_evening_vscode/assets/171637/132e1218-dd60-4c67-bbff-278d3e232b91)
  You can't tell that I only selected the first word of the string ("Pastel").  
  <span></span>
  Another example:
  ![image](https://github.com/kaiusl/pastel_evening_vscode/assets/171637/ef148992-7bd4-4eb5-9c1c-bdbefaaf5f3a)
  In this example, I selected `Extensions` in `settingsSync.ignoredExtensions`. I also hovered over `hediet.vscode-drawio.theme` without a selection.

**Comment by Meligy** [comment]
Side note:

The "FF" at the end of `editor.inactiveSelectionBackground` triggered a warning from VS Code:

<img width="1044" alt="image" src="https://github.com/kaiusl/pastel_evening_vscode/assets/171637/62a1a5af-1379-4a6d-99cb-64eb56b82d4e">

Changing it to even "FE" makes the warning goes away, but I was not able to test it anyway.

Not saying it's something bad or anything. Just thought you'd want to know it's a thing!

Thanks again.

**Comment by kaiusl** [comment]
> 2\. How the selection color matches the hover effect of many other tokens. Like a reference match or a string highlight.

Ah, that's indeed an issue. I'll try to figure something out for them. Meanwhile if you want to change it yourself the relevant keys to modify are
```json
"workbench.colorCustomizations": {
    "[Pastel Evening Dark]": {
        "editor.wordHighlightStrongBackground": "#324454ff",
        "editor.wordHighlightBackground": "#324454ff",
        "editor.hoverHighlightBackground": "#324454ff",
        "editor.symbolHighlightBackground": "#324454ff",
        "editor.selectionHighlightBackground": "#324454ff",
        "editor.rangeHighlightBackground": "#324454ff",
        "editor.findRangeHighlightBackground": "#324454ff",
        "editor.focusedStackFrameHighlightBackground": "#324454ff",
        "editor.snippetTabstopHighlightBackground": "#324454ff",
        "editor.stackFrameHighlightBackground": "#324454ff",
        "editor.snippetFinalTabstopHighlightBackground": "#324454ff",
    }
}
```

**Comment by kaiusl** [comment]
> Side note:
> 
> The "FF" at the end of `editor.inactiveSelectionBackground` triggered a warning from VS Code:
> <img alt="image" width="1044" src="https://private-user-images.githubusercontent.com/171637/292856868-62a1a5af-1379-4a6d-99cb-64eb56b82d4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1OTU2MTksIm5iZiI6MTcwMzU5NTMxOSwicGF0aCI6Ii8xNzE2MzcvMjkyODU2ODY4LTYyYTFhNWFmLTEzNzktNGE2ZC05OWNiLTY0ZWI1NmI4MmQ0ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNlQxMjU1MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZGE2ODI5MWUzYzc3OWM1NDNlMmVmMTJkOTllZjlkMDc1NmVmZDI3YjEzMDFmZjI1NGJkYmI0NzkxOGNhMjg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eyhdXMrHHmQLLoU2gy3XHcJ1pfKqs9FoJSTBT8zolAQ">
> 
> Changing it to even "FE" makes the warning goes away, but I was not able to test it anyway.
> 
> Not saying it's something bad or anything. Just thought you'd want to know it's a thing!

Thanks, hadn't noticed that before. The property description says: "Color of the selection in an inactive editor. The color must not be opaque so as not to hide underlying decorations." but on a quick test I couldn't see the decorations disappearing. Nonetheless probably should change the color to something non opaque in future versions.

**Comment by kaiusl** [comment]
New [v0.3.1](https://github.com/kaiusl/pastel_evening_vscode/releases/tag/v0.3.1) released which fixes the opaque selection colors and conflicting selection and editor highlight colors. The selection color itself remains roughly as it was.

**Comment by Meligy** [comment]
Thanks a lot.
